plugin: aws_ec2
regions:
  - "us-east-1" # hard code us-east-1
filters:
  instance-state-name: running
  tag:Project: JenkinsSandbox # Filter by the 'Project' tag we set in Terraform
  tag:Environment: dev        # Filter by the 'Environment' tag
keyed_groups:
  - key: tags.Name
    prefix: tag_
  - key: tags.Environment
    prefix: env_
  - key: tags.Project
    prefix: project_
compose:
  ansible_host: public_ip
